### ISSUE TITLE
Issue when starting t

### ISSUE THREAD

**Issue by billbarni** [FutureCitiesCatapult/TomboloVisualisationSuite#1]
I get this error when trying to run the application:

```
 error: [tombolo-viewer] Error connecting to DB: SequelizeDatabaseError: function uuid_generate_v4() does not exist
    at Query.formatError (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\sequelize\lib\dialects\postgres\query.js:351:16)
    at query.catch.err (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\sequelize\lib\dialects\postgres\query.js:86:18)
    at tryCatcher (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
2018-02-09T18:33:30.218Z - error: [tombolo-viewer] Could connect to database SequelizeDatabaseError: function uuid_generate_v4() does not exist
    at Query.formatError (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\sequelize\lib\dialects\postgres\query.js:351:16)
    at query.catch.err (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\sequelize\lib\dialects\postgres\query.js:86:18)
    at tryCatcher (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\William\Desktop\TomboloVisualisationSuite\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

I've tried to use mysql (mysql2 package) and got a very 'similar' error... similar because it happens in the same uuid_generate_v4() function but with an SQL sintax error.

Can you point me to why this problem occurs?

Thanks for sharing this project, the code is really interesting and built with amazing tech (typedi, typeorm and nice validators).

**Comment by robinsummerhill** [comment]
Hi Bill,

This project is at a very early stage of active development in a collaboration between Future Cities and Emu Analytics. We’ll provide full build and run instructions at a later date. Stay tuned!

The specific error you are seeing is because you don’t have the uuid-ossp Postgres extension installed. Do `create extension uuid-ossp;` in psql or your DB admin tool of choice to install it. By the way, the project will only work with Postgres+PostGIS because it makes extensive use of spatial data types.

Robin - lead architect and developer
Emu Analytics

**Comment by billbarni** [comment]
Thank you very much for the clarification. Great work.
